import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// --- Merge CSS: ccmd-system + legacy ---
// Tailwind 已于 M7 P2-7 退役；样式全部由 ccmd-system.css（语义设计系统）
// 与 styles.legacy.css（残留 ccmd 规则）提供。
function mergeCSS() {
	// ccmd-system.css 优先（语义设计系统，绑定 Obsidian 主题变量）
	const ccmdCSS = fs.existsSync("src/styles/ccmd-system.css")
		? fs.readFileSync("src/styles/ccmd-system.css", "utf-8")
		: "";
	// legacy 放最后，保持覆盖优先级
	const legacyCSS = fs.existsSync("styles.legacy.css")
		? fs.readFileSync("styles.legacy.css", "utf-8")
		: "";

	const merged = `/* === ccmd design system === */\n${ccmdCSS}\n\n/* === Legacy styles === */\n${legacyCSS}`;

	// Ensure dist directory exists
	if (!fs.existsSync("dist")) {
		fs.mkdirSync("dist", { recursive: true });
	}

	fs.writeFileSync("styles.css", merged);
	console.log("[CSS] styles.css merged successfully.");
}

// Build CSS before JS
mergeCSS();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "dist/main.js",
	minify: prod,
	jsx: "automatic",
	jsxImportSource: "react",
	resolveExtensions: [".tsx", ".ts", ".jsx", ".js"],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
